class Bird{
    constructor(){
        this.y=height/2
    this.x=64
    this.gravity=0.7
    this.lift=-12
    this.velocity=0
    }
    show(){
        fill('black')
        ellipse(this.x,this.y,30,30)
    }
    up(){
        this.velocity=this.velocity+this.lift
    }
    update(){
        this.velocity=this.velocity+this.gravity
        this.y=this.y+this.velocity
        if(this.y>height){
        this.y=height
        this.velocity=0
        }
        if(this.y<0){
        this.y=0
        this.velocity=0
        }
    }
}